#!/usr/bin/env bash
#

echo "Starting build process..."
echo "Removing old site..."
rm -rf ./www/*
echo "Building new site..."
podman run --rm --name showroom-builder --platform linux/amd64 -v "./:/antora" docker.io/antora/antora zero-touch-site.yml
#podman run --rm --name showroom-builder --platform linux/amd64 -v "./:/antora" docker.io/antora/antora site.yml
echo "Build process complete. Check the ./www folder for the generated site."
 if test -f "/tmp/nookbag.zip"; then
    echo "UI already downloaded."
else
    wget -q https://github.com/rhpds/nookbag/releases/download/nookbag-v0.0.3/nookbag-v0.0.3.zip -O /tmp/nookbag.zip 
fi
tar -xf /tmp/nookbag.zip -C ./www/
cp ./zero-touch-config.yml ./www/
echo "To view the site locally, run the following command: utilities/serve.sh"
echo "If already running then browse to http://localhost:8080/index.html"
